para:
  train_batch_size: 10000
  train_small_batch_size: 20
  test_size: 10000
  full_iterations: 100
  enc_train_iters: 5
  dec_train_iters: 25

  lr: 0.0001
  seed: 1

  # log_interval: 100
  # epoch_size : 200
  
  n: 41
  r: 2
  m: 6


  # Use in train validate data util
  enc_train_snr: -2
  dec_train_snr: -4
 
  data_type: "n4_r2_m3"
  logger_name: C_{}_train
  CUDA_VISIBLE_DEVICES: "1"
  train_save_path_dir: "./save/{}/C_{}"
  train_save_path_encoder: "./save/{}/C_{}/enc_{}.pth"
  train_save_path_decoder: "./save/{}/C_{}/dec_{}.pth"
  # test_model_path: ./save/C_{}/C_{}_1.pth

  # Retraining parameters
  retrain: False
  retrain_day: Jan-05-2022
  retrain_epoch_num: 21

test:
 # Use in test_ber
  # snr_list: 1,2,3,4,5,6
  Boosting_number_list: 1,2,3
  day: Jan-16-2022
  epoch_num: 100
  logger_name: C_{}_test
  test_model_path_encoder: "./save/{}/C_{}/enc_{}.pth"
  test_model_path_decoder: "./save/{}/C_{}/dec_{}.pth"
